### ISSUE TITLE
When sendinblue module is enable Login as customer is KO

### ISSUE THREAD

**Issue by cmiault** [sendinblue/magento2-plugin#14]
Hello,

In Magento 2 BO, customers list
Choose a customer
From the customer page click on "login as customer"
The page in FO has a php error :

Error: Call to undefined method Magento\LoginAsCustomerFrontendUi\Controller\Login\Index\Interceptor::getResponse() in /home/magento/sites/magento/sources/app/code/Sendinblue/Sendinblue/Observer/SibAutomationObserver.php:49 Stack trace: #0 /home/magento/sites/magento/sources/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Sendinblue\Sendinblue\Observer\SibAutomationObserver->execute(Object(Magento\Framework\Event\Observer)) #1 /home/magento/sites/magento/sources/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Sendinblue\Sendinblue\Observer\SibAutomationObserver), Object(Magento\Framework\Event\Observer)) #2 /home/magento/sites/magento/sources/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer)) #3 /home/magento/sites/magento/sources/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('controller_acti...', Array) #4 /home/magento/sites/magento/sources/vendor/magento/framework/App/Action/Plugin/EventDispatchPlugin.php(108): Magento\Framework\Event\Manager\Proxy->dispatch('controller_acti...', Array) #5 /home/magento/sites/magento/sources/vendor/magento/framework/App/Action/Plugin/EventDispatchPlugin.php(60): Magento\Framework\App\Action\Plugin\EventDispatchPlugin->dispatchPreDispatchEvents(Object(Magento\LoginAsCustomerFrontendUi\Controller\Login\Index\Interceptor)) #6 /home/magento/sites/magento/sources/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Framework\App\Action\Plugin\EventDispatchPlugin->beforeExecute(Object(Magento\LoginAsCustomerFrontendUi\Controller\Login\Index\Interceptor)) #7 /home/magento/sites/magento/sources/vendor/magento/framework/Interception/Interceptor.php(153): Magento\LoginAsCustomerFrontendUi\Controller\Login\Index\Interceptor->Magento\Framework\Interception\{closure}() #8 /home/magento/sites/magento/sources/generated/code/Magento/LoginAsCustomerFrontendUi/Controller/Login/Index/Interceptor.php(26): Magento\LoginAsCustomerFrontendUi\Controller\Login\Index\Interceptor->___callPlugins('execute', Array, Array) #9 /home/magento/sites/magento/sources/vendor/magento/framework/App/FrontController.php(188): Magento\LoginAsCustomerFrontendUi\Controller\Login\Index\Interceptor->execute() #10 /home/magento/sites/magento/sources/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\LoginAsCustomerFrontendUi\Controller\Login\Index\Interceptor)) #11 /home/magento/sites/magento/sources/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http)) #12 /home/magento/sites/magento/sources/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array) #13 /home/magento/sites/magento/sources/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #14 /home/magento/sites/magento/sources/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #15 /home/magento/sites/magento/sources/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #16 /home/magento/sites/magento/sources/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #17 /home/magento/sites/magento/sources/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #18 /home/magento/sites/magento/sources/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL) #19 /home/magento/sites/magento/sources/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #20 /home/magento/sites/magento/sources/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch() #21 /home/magento/sites/magento/sources/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #22 {main}

If I disable sendinblue module this functionnality works correctly.

Best regards

**Comment by sahilbabu** [comment]
I'm facing same issue 

[2023-10-31T07:38:26.765261+00:00] main.CRITICAL: Error: Call to undefined method Geissweb\Euvat\Controller\Vatnumber\Validation\Interceptor::getResponse() in app/code/Sendinblue/Sendinblue/Observer/SibAutomationObserver.php:49
Stack trace:
#0 /home/prod/release/1694515638/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Sendinblue\Sendinblue\Observer\SibAutomationObserver->execute()
#1 /home/prod/release/1694515638/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#2 /home/prod/release/1694515638/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#3 /home/prod/release/1694515638/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch()
#4 /home/prod/release/1694515638/vendor/magento/framework/App/FrontController.php(271): Magento\Framework\Event\Manager\Proxy->dispatch()
#5 /home/prod/release/1694515638/vendor/magento/framework/App/FrontController.php(211): Magento\Framework\App\FrontController->dispatchPreDispatchEvents()
#6 /home/prod/release/1694515638/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#7 /home/prod/release/1694515638/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#8 /home/prod/release/1694515638/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#9 /home/prod/release/1694515638/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#10 /home/prod/release/1694515638/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#11 /home/prod/release/1694515638/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#12 /home/prod/release/1694515638/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#13 /home/prod/release/1694515638/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#14 /home/prod/release/1694515638/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#15 /home/prod/release/1694515638/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#16 /home/prod/release/1694515638/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#17 /home/prod/release/1694515638/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#18 /home/prod/release/1694515638/pub/index.php(30): Magento
